[11.0] [MIG] purchase_operating_unit
OCA/operating-unit pull request #168
Opened 2019-02-06 09:49 UTC by bjeficent

Migration of purchase_operating_unit to v11

2019-02-06 10:38 UTC, nikul-serpentcs reviewed
Improve Code

2019-02-06 10:38 UTC, nikul-serpentcs commented on purchase_operating_unit/__manifest__.py
> +    "website": "http://www.eficent.com",
@bjeficent URL Should be `https://github.com/OCA/operating-unit`

2019-03-19 10:14 UTC, nikul-serpentcs requested changes
Improve Copyright

2019-03-19 10:14 UTC, nikul-serpentcs commented on purchase_operating_unit/__manifest__.py
> +# © 2015-17 Serpent Consulting Services Pvt. Ltd. - Sudhir Arya
© -> Copyright and 2015-17 -> 2015-19

2019-03-19 10:59 UTC, bjeficent commented
Comments attended, thanks for reviewing.

2019-03-20 19:32 UTC, danypr92 approved these changes

2019-03-22 16:38 UTC, enricostano approved these changes

2019-10-29 10:08 UTC, aheficent commented
@nikul-serpentcs Could you please update your review bro?

2019-11-02 05:30 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2019-11-02 23:24 UTC, aheficent commented
Oops I pushed from the wrong place. I will fix that.

2019-11-03 09:22 UTC, aheficent commented
Github detects the commit hash is the same so it will not reconsider the user. I created a duplicate of this PR here #210

2019-11-03 09:23 UTC, closed without merging

2019-11-03 10:59 UTC, aheficent commented
:+1: Tested