[11.0] [MIG] mis_builder_operating_unit
OCA/operating-unit pull request #170
Opened 2019-02-06 09:50 UTC by bjeficent

Migration of mis_buider_operating_unit to v11

2019-02-06 18:07 UTC, Nikul-Chaudhary reviewed
Improved Code

2019-02-06 18:07 UTC, Nikul-Chaudhary commented on mis_builder_operating_unit/security/mis_builder_security.xml
> +<data noupdate="0">
@bjeficent no need `data`

2019-02-15 07:17 UTC, bjeficent commented
Comments attended, thanks for reviewing.

2019-02-19 04:29 UTC, nikul-serpentcs requested changes
Improve Code

2019-02-19 04:29 UTC, nikul-serpentcs commented on mis_builder_operating_unit/model/mis_builder.py
> +                                          required=False)
@bjeficent no need to `required=False`, It's already `False`

2019-02-19 04:29 UTC, nikul-serpentcs commented on mis_builder_operating_unit/model/mis_builder.py
> +                                          required=False)
same here

2019-03-22 16:40 UTC, enricostano approved these changes

2019-10-28 15:03 UTC, AaronHForgeFlow approved these changes
:+1: LGTM

@nikul-serpentcs  can you update your review, please?

2019-11-02 09:20 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2019-11-02 10:24 UTC, sbidoul approved these changes
LGTM

2019-11-02 23:04 UTC, aheficent commented
/ocabot merge

2019-11-02 23:12 UTC, merged

2019-11-21 21:34 UTC, TheCloneMaster commented
@bjeficent do you have any idea of possible changes from v11 to v12?
I would like to help porting to v12...

2019-11-22 13:28 UTC, aheficent commented
@TheCloneMaster Please see https://github.com/OCA/operating-unit/pull/211