[12.0] [MIG] sale_stock_operating_unit
OCA/operating-unit pull request #174
Opened 2019-02-11 13:03 UTC by bjeficent

Migration of sale_stock_operating_unit to version 12.0

2019-02-12 03:57 UTC, nikul-serpentcs requested changes
Improve Code

2019-02-12 03:57 UTC, nikul-serpentcs commented on sale_stock_operating_unit/models/sale_order.py
> +            warehouses = self.env['stock.warehouse'].search(
Use `limit=1`

2019-02-12 03:57 UTC, nikul-serpentcs commented on sale_stock_operating_unit/models/sale_order.py
> +            warehouses = self.env['stock.warehouse'].search(
same here

2019-02-12 10:09 UTC, bjeficent commented
Comments attended, thanks for reviewing.

2019-03-19 10:05 UTC, nikul-serpentcs requested changes
Minor change

2019-03-19 10:05 UTC, nikul-serpentcs commented on sale_stock_operating_unit/__manifest__.py
> +# © 2015-19 Eficent Business and IT Consulting Services S.L. -
© - > Copyright in all file

2019-03-19 10:54 UTC, bjeficent commented
Comments attended, thanks for reviewing.

2019-11-26 15:21 UTC, MiquelRForgeFlow approved these changes
LGTM

2019-11-28 12:11 UTC, AaronHForgeFlow approved these changes
:+1: Functional test + code

2019-11-28 12:13 UTC, aheficent commented
Hi @nikul-serpentcs could you update your review please? Thank you.

2019-12-01 07:34 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2019-12-18 14:33 UTC, AaronHForgeFlow commented
/ocabot merge

2019-12-18 14:50 UTC, merged