[12.0] [MIG] purchase_request_operating_unit
OCA/operating-unit pull request #175
Opened 2019-02-13 11:14 UTC by bjeficent

Migration to v12 of purchase_request_operating_unit merged with purchase_request_to_rfq_operating_unit

2019-02-13 11:16 UTC, nikul-serpentcs commented on purchase_request_operating_unit/__manifest__.py
> +    "website": "http://www.eficent.com",
https://github.com/OCA/operating-unit

2019-02-13 11:18 UTC, nikul-serpentcs requested changes
Improved COde

2019-02-13 11:18 UTC, nikul-serpentcs commented on purchase_request_operating_unit/model/purchase_request.py
> +        string='Operating Unit', readonly=True,
no need to ` readonly=True`

2019-02-13 11:18 UTC, nikul-serpentcs commented on purchase_request_operating_unit/security/purchase_security.xml
> +<odoo noupdate="0">
no need `noupdate="0"`

2019-02-13 11:18 UTC, nikul-serpentcs commented on purchase_request_operating_unit/view/purchase_request_view.xml
> +<odoo noupdate="0">
same here

2019-02-13 12:19 UTC, bjeficent commented
Comments attended, thanks for reviewing

2019-03-19 10:01 UTC, nikul-serpentcs requested changes
Improve Copyright in all file

2019-03-19 10:01 UTC, nikul-serpentcs commented on purchase_request_operating_unit/__init__.py
> +# Copyright 2016-17 Serpent Consulting Services Pvt. Ltd.
Copyright 2016-17 ->  Copyright 2016-19

2019-03-19 10:50 UTC, bjeficent commented
Comments attended, thanks for reviewing.

2019-11-25 14:25 UTC, AaronHForgeFlow approved these changes
:+1: Functional review LGTM

2019-11-25 14:30 UTC, MiquelRForgeFlow approved these changes
LGTM

2019-11-25 16:55 UTC, aheficent commented
/ocabot merge

2019-11-25 17:12 UTC, merged