[ADD][9.0] hr payroll account operating unit
OCA/operating-unit pull request #25
Opened 2016-09-14 16:34 UTC by aheficent

This module introduces the following features:

* Adds Operating Unit (OU) to the account moves and its lines created by the payslip, based on the Operating Unit (OU) defined in the Employee's Contract.

2017-04-06 16:38 UTC, aheficent commented
ping @eficent

2017-04-06 17:03 UTC, lreficent commented on hr_payroll_account_operating_unit/README.rst
> +=====
remove empty sections and also to add some lines in the usage would be good.

2017-04-07 08:27 UTC, LoisRForgeFlow approved these changes
LGTM :+1:

2017-11-07 16:47 UTC, MiquelRForgeFlow approved these changes

2017-11-22 11:30 UTC, andhit-r requested changes

2017-11-22 11:30 UTC, andhit-r commented on hr_payroll_account_operating_unit/models/account_move.py
> +    def create(self, vals):
@aheficent IMO this method should be in account_operating_unit module since there is a possibility that the method will be use by other module.

2019-10-01 14:02 UTC, aheficent commented
Not working on this anymore

2019-10-01 14:02 UTC, closed without merging