complete filter also in name search
OCA/operating-unit pull request #305
Opened 2020-07-16 11:55 UTC by andreampiovesana

if you start to insert a partner you visualize all, with this you immediately filter partner by operating-unit

2020-07-22 11:24 UTC, gregoril approved these changes
Tested, it works correctly

2020-08-07 20:32 UTC, patrickrwilson approved these changes
Tested and works as intended.

2021-05-08 22:05 UTC, dreispt commented
/ocabot merge patch

2021-05-09 01:02 UTC, marcelsavegnago requested changes
Please check travis error

2022-06-19 12:26 UTC, closed without merging