[FIX] operating_unit: remove duplicate reference
OCA/operating-unit pull request #413
Opened 2021-08-17 19:22 UTC by sswapnesh

Record `b2b_operating_unit` was referenced twice.

2021-08-18 06:54 UTC, AaronHForgeFlow approved these changes

2021-08-18 06:59 UTC, AaronHForgeFlow requested changes
For some reason the operating units ids are empty for demo user in runbot. Can you check?

![2021-08-18_08-58](https://user-images.githubusercontent.com/19620251/129852486-d5998618-4c44-415b-9dd5-4f08bba081d4.png)

2021-08-19 11:33 UTC, sswapnesh commented
@AaronHForgeFlow  Updated, Not sure why it was not Working even we are assign it in 

https://github.com/OCA/operating-unit/blob/70a232bad1844cbe440c2a0ce8d0c37606973bbf/operating_unit/models/res_users.py#L64

2021-08-21 10:08 UTC, flotho requested changes
Deleting some operating_units on the user don't seems to be stored properly : 
![image](https://user-images.githubusercontent.com/1043935/130318448-520d02a3-5579-4589-828d-f0871358793e.png)

after validation  : 
![image](https://user-images.githubusercontent.com/1043935/130318459-d713d243-62af-45ca-a533-fb19b4e3f9fe.png)

2021-08-22 14:44 UTC, sswapnesh commented
@flotho I believe It has nothing to do with this PR. 
IMO this should be added as new Issue.

2021-09-08 17:26 UTC, sswapnesh commented
@AaronHForgeFlow  Can it be merged ?

2021-10-08 14:20 UTC, AaronHForgeFlow approved these changes
LGTM

2021-10-08 14:21 UTC, AaronHForgeFlow commented
@flotho I thing that is not related to this PR so that probably needs to be fixed in another PR. Do you agree?

2021-12-04 18:34 UTC, dreispt commented
/ocabot merge minor

2021-12-04 23:27 UTC, merged