[MIG] crm_operating_unit to v10.0
OCA/operating-unit pull request #48
Opened 2017-01-26 13:26 UTC by lreficent

CRM with Operating Units
=========================

This module introduces the following features:

* Adds the Operating Unit (OU) to the Lead.

* The user’s default Operating Unit (OU) is proposed at the time of creating the Lead / Opportunity.

* Security rules are defined to ensure that users can only see the Opportunity / Lead of that Operating Units in which they are allowed access to.

2017-01-26 13:42 UTC, lreficent commented
depends on https://github.com/OCA/operating-unit/pull/45

2017-01-27 09:32 UTC, lreficent commented
Ready to merge I think. Can you review?

cc @aheficent @jbeficent @darshan-serpent @mreficent @guewen

2017-01-27 12:21 UTC, AaronHForgeFlow approved these changes
:+1: all good

2017-01-27 12:31 UTC, serpentcs-dev1 requested changes

2017-01-27 12:31 UTC, darshan-serpent commented on crm_operating_unit/models/__init__.py
>  # © 2015 Serpent Consulting Services Pvt. Ltd. - Sudhir Arya
Please make it 2016-17 for all contributors

2017-01-29 07:53 UTC, serpentcs-dev1 approved these changes

2017-01-31 10:41 UTC, JordiBForgeFlow approved these changes

2017-01-31 10:41 UTC, merged