10.0 mig account budget operating unit
OCA/operating-unit pull request #53
Opened 2017-01-26 14:22 UTC by aheficent

=============================
Account Budget Operating Unit
=============================

This module introduces the following features:

* Adds the OU as a required field in the budget plan / budget line

* Security rules are defined to ensure that users can only display the
  budget in which they are allowed access to.

# Depends on https://github.com/OCA/operating-unit/pull/50

2017-01-27 12:32 UTC, serpentcs-dev1 requested changes

2017-01-27 12:32 UTC, darshan-serpent commented on account_budget_operating_unit/models/account_budget.py
> +    @api.one
Hmm.. api.one is deprecated isn'it? 
cc: @jbeficent

2017-01-27 15:56 UTC, LoisRForgeFlow approved these changes
:+1:

2018-06-29 08:34 UTC, serpentcs-dev1 approved these changes
Code Review :+1:

2019-03-07 16:41 UTC, aheficent commented
Closing as nobody cares

2019-03-07 16:41 UTC, closed without merging