[15.0][ADD] purchase_deposit_operating_unit
OCA/operating-unit pull request #557
Opened 2023-02-02 02:42 UTC by Saran440

This module allow create invoice (deposit) with not default operating unit in invoices

If not install this module, you can not create invoice (deposit) with not default operating unit
Example:
Admin has 3 OU = Main, B2B, B2C
default ou is Main
If admin create purchase order with B2B and register deposit it will error because it not send operating unit B2B to invoice
![Selection_002](https://user-images.githubusercontent.com/20896369/216217840-a6de8ff8-b6e0-4043-b194-d98ada6d2493.png)

2025-07-24 14:27 UTC, AaronHForgeFlow commented
Hi @Saran440 . Is your PR still valid? It seems to me that the need is still valid.

2025-07-24 14:34 UTC, AaronHForgeFlow approved these changes
Functional review :+1: 

Sorry for the late review :cry:

2025-07-30 06:40 UTC, AaronHForgeFlow requested changes
Just pending to fix the tests. I may supersede this in another PR if you don't expect further work on this one. Thanks:

```
2025-07-24 14:30:48,913 413 ERROR odoo odoo.addons.purchase_deposit_operating_unit.tests.test_purchase_deposit_operating_unit: ERROR: TestPurchaseDeposit.test_create_deposit_invoice
Traceback (most recent call last):
  File "/__w/operating-unit/operating-unit/purchase_deposit_operating_unit/tests/test_purchase_deposit_operating_unit.py", line 108, in test_create_deposit_invoice
    invoice = self.invoice_model.browse(res["res_id"])
KeyError: 'res_id'
```

2025-07-31 14:39 UTC, Saran440 commented
@AaronHForgeFlow Yes, we use this in production.
I will fix red test ASAP.

2025-08-04 07:20 UTC, Saran440 commented
@AaronHForgeFlow Fixed test script. :)

2025-08-04 08:20 UTC, AaronHForgeFlow approved these changes
@Saran440 Thank you!

LGTM Functional + code

2025-08-04 08:41 UTC, Pani-k-folk approved these changes
CODE LGTM :+1:

2025-08-04 08:46 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2025-08-04 08:57 UTC, merged