[15.0][MIG] project_operating_unit: migration to 15.0
OCA/operating-unit pull request #577
Opened 2023-03-17 15:17 UTC by huguesdk

2023-03-21 14:55 UTC, alan196 requested changes
Only one comment

2023-03-21 14:55 UTC, alan196 commented on project_operating_unit/models/project_task.py
> -        default=lambda self: self.env["res.users"].operating_unit_default_get(
Why do you remove the default?

2023-03-21 15:05 UTC, huguesdk commented on project_operating_unit/models/project_task.py
> -        default=lambda self: self.env["res.users"].operating_unit_default_get(
thanks for the review!

with the default, odoo gives the following warning:
```
odoo.fields: Redundant default on project.task.operating_unit_id
```
indeed, it’s a related field and the default value is the same on the original field.

2023-03-21 15:19 UTC, alan196 commented on project_operating_unit/models/project_task.py
> -        default=lambda self: self.env["res.users"].operating_unit_default_get(
Sorry, I didn't notice it was a related field.

2023-03-21 15:20 UTC, alan196 approved these changes
👍 Technical review

2023-08-02 12:54 UTC, alan196 commented
@EduardoJarsa @hectorHerreraTeigeiro could you help me to review this PR?

2023-08-02 14:12 UTC, EduardoJarsa reviewed
functional review looks works

2023-08-02 14:32 UTC, EduardoJarsa approved these changes
Functional review, everything looks working

2023-08-02 21:38 UTC, hectorHerreraTeigeiro commented on project_operating_unit/models/project_task.py
> -        default=lambda self: self.env["res.users"].operating_unit_default_get(
Looks complete for me

2023-08-09 11:10 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2023-08-09 11:22 UTC, merged