[16.0] [MIG] sale_operating_unit
OCA/operating-unit pull request #600
Opened 2023-06-22 08:18 UTC by Borruso

Migration hr_operating_unit from 15.0 to 16.0
Depends https://github.com/OCA/operating-unit/pull/596 and https://github.com/OCA/operating-unit/pull/592

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

2023-07-20 10:50 UTC, AaronHForgeFlow commented
Can you apply this? https://github.com/OCA/operating-unit/pull/612 Thanks

2023-08-22 16:52 UTC, alan196 requested changes

2023-08-22 16:52 UTC, alan196 commented on sale_operating_unit/models/sale_order.py
> +            self.team_id = False
```suggestion
            self.team_id = False
        if self.operating_unit_id:
            self.team_id = self.env["crm.team"].search(
                [("operating_unit_id", "=", self.operating_unit_id.id)], limit=1
            )
```

To set a team when the operating unit is changed

2023-08-24 15:11 UTC, alan196 approved these changes
Technical & Funcional review 👍

2023-09-04 19:11 UTC, alan196 requested changes

2023-09-04 19:11 UTC, alan196 commented on sale_operating_unit/wizard/sale_make_invoice_advance.py
> +        return invoice
```suggestion
        return invoice
        
            def _prepare_invoice_values(self, order, name, amount, so_line):
        invoice_vals = super(SaleAdvancePaymentInv, self)._prepare_invoice_values(
            order, name, amount, so_line
        )
        journal = self.env["account.journal"].search(
            [
                ("operating_unit_id", "=", order.operating_unit_id.id),
                ("type", "=", "sale"),
            ],
            limit=1,
        )
        if not journal:
            raise ValidationError(
                _("You need to create a sales journal for this operating unit.")
            )
        invoice_vals.update(
            {
                "operating_unit_id": order.operating_unit_id.id,
                "journal_id": journal.id,
            }
        )
        return invoice_vals

```

I added this in order to allow to create invoices from the same OU when a user has access to multiple OU by default it shows the default OU of the user and not the OU of the sale order.

2023-09-04 19:44 UTC, alan196 commented
I detected an issue and make PR https://github.com/Borruso/operating-unit/pull/1 to fix it

2023-09-07 23:19 UTC, max3903 commented
/ocabot migration sale_operating_unit

2024-07-30 12:55 UTC, AaronHForgeFlow commented
/ocabot rebase

2024-07-30 13:17 UTC, AaronHForgeFlow approved these changes
Functional LGTM. In v15 the issue commented exists as well so maybe we can merge this and propose a new PR for the fix.

2024-09-12 14:46 UTC, AaronHForgeFlow commented
Pending to include this small improvement: https://github.com/OCA/operating-unit/pull/706/

2024-11-08 10:13 UTC, Borruso commented
> Pending to include this small improvement: #706

commit included

2025-04-16 09:21 UTC, tarteo requested changes
I'm not sure if this should be a separate module like website_sale_operating_unit or it should be handled here

**To reproduce:**

1. Install website_sale;
2. create a product and publish it;
3. make sure the sales team is set to "Website" on the website (this is by default)
5. create a OU "Online Orders" or whatever and change the operating unit on the sales team to it
6. go to /shop and click "Add to Cart" 

This error occurs:
```Configuration error. The Operating Unit of the sales team must match with that of the quote/sales order.```

![image](https://github.com/user-attachments/assets/5a9456c5-15db-4773-b5d0-a74f2afbf526)

2025-04-16 09:24 UTC, AaronHForgeFlow commented
Is it solved by assigning the new operating unit to the portal user?

2025-04-16 09:28 UTC, tarteo commented
@AaronHForgeFlow No, also not for the public user or any internal user

2025-04-16 09:38 UTC, AaronHForgeFlow commented
I see. Perhaps a new module website_sale_operating_unit makes more sense to me.

2025-04-16 10:05 UTC, tarteo commented
@Borruso I fixed it:

```
    
    operating_unit_id = fields.Many2one(
        comodel_name="operating.unit",
        string="Operating Unit",
        compute="_compute_operating_unit_id",
        inverse="_inverse_operating_unit_id",
        store=True,
        readonly=True,
        states={"draft": [("readonly", False)], "sent": [("readonly", False)]},
    )

    @api.onchange("team_id")
    @api.depends("team_id", "team_id.operating_unit_id")
    def _compute_operating_unit_id(self):
        for sale in self:
            sale.operating_unit_id = sale.team_id.operating_unit_id
    
    @api.onchange("operating_unit_id")
    def _inverse_operating_unit_id(self):
        for sale in self:
            sale.team_id = self.env["crm.team"].search(
                [("operating_unit_id", "=", sale.operating_unit_id.id)], limit=1
            )
```

2025-04-16 10:13 UTC, tarteo commented
@Borruso @AaronHForgeFlow I fixed it by replacing it with compute and inverse but keeping the onchanges for ux

```
    
    operating_unit_id = fields.Many2one(
        comodel_name="operating.unit",
        string="Operating Unit",
        compute="_compute_operating_unit_id",
        inverse="_inverse_operating_unit_id",
        store=True,
        readonly=True,
        states={"draft": [("readonly", False)], "sent": [("readonly", False)]},
    )

    @api.onchange("team_id")
    @api.depends("team_id", "team_id.operating_unit_id")
    def _compute_operating_unit_id(self):
        for sale in self.filtered(lambda s: s.state in ("draft", "sent")):
            sale.operating_unit_id = sale.team_id.operating_unit_id
    
    @api.onchange("operating_unit_id")
    def _inverse_operating_unit_id(self):
        for sale in self.filtered(lambda s: s.state in ("draft", "sent")):
            sale.team_id = self.env["crm.team"].search(
                [("operating_unit_id", "=", sale.operating_unit_id.id)], limit=1
            )

```

2025-04-16 10:21 UTC, AaronHForgeFlow commented
I am ok with that change @tarteo  Thank you for the fix.

2025-06-27 08:39 UTC, matteonext approved these changes
Functional ok! Any news about it?

2025-06-27 13:14 UTC, marcelsavegnago approved these changes
LGTM

2025-06-30 08:09 UTC, AaronHForgeFlow commented
Perhaps we could merge this and then so the fix in a separate PR @tarteo Is that fine?

2025-07-04 07:46 UTC, tarteo commented
@AaronHForgeFlow Yes, lets move forward (sorry late response)

2025-07-04 09:51 UTC, AaronHForgeFlow commented
@tarteo  Thank you.

/ocabot merge nobump

2025-07-04 09:57 UTC, merged