[13.0][IMP] account_operating_unit: added migration scripts
OCA/operating-unit pull request #609
Opened 2023-07-19 09:37 UTC by AaronHForgeFlow

Operating units should be passed from invoices when migrating. This assumes the database was migrated using OpenUpgrade

@ForgeFlow @MiquelRForgeFlow

2023-07-19 10:42 UTC, MiquelRForgeFlow requested changes

2023-07-19 10:42 UTC, MiquelRForgeFlow commented on account_operating_unit/migrations/13.0.1.0.0/post-migration.py
> +        AND aml.operating_unit_id is NULL""",
```suggestion
        FROM account_invoice_line ail
        WHERE aml.old_invoice_line_id = ail.id
        AND aml.operating_unit_id is NULL""",
```

2023-09-29 13:24 UTC, MiquelRForgeFlow approved these changes

2023-09-29 13:27 UTC, JordiMForgeFlow approved these changes
LGTM

2023-09-29 13:28 UTC, MiquelRForgeFlow approved these changes

2023-09-29 13:28 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2023-09-29 13:34 UTC, merged