[16.0] migration of sale_stock_operating_unit
OCA/operating-unit pull request #614
Opened 2023-07-27 00:48 UTC by alan196

This PR depends on https://github.com/OCA/operating-unit/pull/600 and https://github.com/OCA/operating-unit/pull/598

2023-09-07 23:18 UTC, max3903 commented
/ocabot migration sale_stock_operating_unit

2025-08-26 15:51 UTC, francesco-ooops commented
@AaronHForgeFlow @alan196 can you rebase? Runboat is not available

2025-08-26 15:53 UTC, AaronHForgeFlow commented
/ocabot rebase

2025-08-27 17:34 UTC, alan196 commented
@francesco-ooops @AaronHForgeFlow I rebased the branch

2025-08-28 08:51 UTC, francesco-ooops requested changes
Functional review: with this module installed, the OU is loaded correctly on SO creation, but as soon as partner is set it's changed to another OU

2025-08-28 13:45 UTC, AaronHForgeFlow approved these changes
functional + light code review

2025-08-28 13:47 UTC, AaronHForgeFlow commented
Hi @francesco-ooops did you expect the OU to be changed based on the partner OU? That is not covered in this module. I am not sure if I understood.

2025-08-28 13:52 UTC, francesco-ooops commented
@AaronHForgeFlow maybe I'm missing something (and I could not reproduce the behavior on branch 16 runboat), but why is OU changing when I change SO partner? [VIDEO](https://www.loom.com/share/beca58ac91fa4fc99b07f6ad4eb19f49)

2025-08-28 14:02 UTC, alan196 commented
@francesco-ooops I think your issue is caused by a method in this module, when you change the sales team, that is taken from the parter, if try to change the warehouse to a warehouse that has the same operating unit as the sales team.

2025-08-28 14:12 UTC, francesco-ooops commented
Where's the sales team in the SO partner? 

I could not reproduce the behavior in v14 or v15, that's why I flagged it

(create new OU > Create new Warehouse with new OU > Create new sales team with new OU > assign Mitchell Admin to new sales team > the NEW OU is set in SO regardless of customer selected)

2025-08-29 11:12 UTC, francesco-ooops commented
@alan196 @AaronHForgeFlow this is the difference I see between this PR and v15: [VIDEO](loom.com/share/dba5e28d41224725811dfd48dd322914?focus_title=1&muted=1&from_recorder=1)

2025-09-10 14:35 UTC, Chionne27 commented
Hi @alan196 @AaronHForgeFlow. I made a new PR #797 with the migration of the module because i effectively noticed the issue reported by @francesco-ooops. The issue was caused because in v17 the modules sale and sale_stock are not properly compatible with the module sale_stock_operating_unit, that adds onchanges instead of interact with existing onchanges/depends. 
For example in v17 we have this function in sale
https://github.com/odoo/odoo/blob/e1fb54cb3d5db9c906946fa11ff49c1ca86d3722/addons/sale/models/sale_order.py#L451
and i think is better to override this function as here 
https://github.com/OCA/operating-unit/blob/745a743208b583fe79602e2012d0400f8979b9c2/sale_stock_operating_unit/models/sale_order.py#L41
instead of making an onchange and it works as it should.
Check my PR and tell me what you think

2025-09-10 17:17 UTC, closed without merging