[MIG][10.0] stock account operating unit
OCA/operating-unit pull request #71
Opened 2017-05-26 15:07 UTC by aheficent

Stock account moves with Operating Unit
=======================================

This module introduces the following features:
- Creates account move lines when stock moves are posted between internal
locations within the same company, but different OU’s.

The PR in v9: https://github.com/OCA/operating-unit/pull/21

2017-05-26 15:08 UTC, aheficent commented
cc @eficent

2017-05-27 01:20 UTC, elicoidal approved these changes
LGTM (no functional tests)

2017-05-27 01:20 UTC, elicoidal commented on stock_account_operating_unit/README.rst
> +   ** Set the "Operating Units are self-balanced" checkbox
insert a blank line

2017-05-27 01:20 UTC, elicoidal commented on stock_account_operating_unit/README.rst
> +* Create an account for "Inter-OU Clearing" of type Regular.
use better "#. " for enumerated list

2017-05-30 12:45 UTC, aheficent commented
Thank you for your review @elicoidal I applied the changes you suggested in the readme

2017-05-31 01:37 UTC, elicoidal approved these changes

2017-05-31 09:31 UTC, aheficent commented
@guewen Can you take a look at this? This module is basic for the operating unit repo, it would control the stock movements between operating units.

2017-06-08 08:10 UTC, MiquelRForgeFlow requested changes

2017-06-08 08:10 UTC, mreficent commented on stock_account_operating_unit/__manifest__.py
> +    "website": "https://github.com/OCA/operating-unit.com",
remove the <code>.com</code>

2017-07-20 14:55 UTC, aheficent commented
Hi @mreficent your comments have been attended :wink:

2017-07-20 15:33 UTC, MiquelRForgeFlow approved these changes

2017-07-24 07:55 UTC, LoisRForgeFlow reviewed
Some comments in line. Plus, to add some test for the UserError would be nice.

2017-07-24 07:55 UTC, lreficent commented on stock_account_operating_unit/README.rst
> +- Creates account move lines when stock moves are posted between internal
This is not being displayed correctly - Use a blank space before this line

2017-07-24 07:55 UTC, lreficent commented on stock_account_operating_unit/model/stock_quant.py
> +        Generate an accounting moves if the product being moved is subject
Generate ~an~ accounting moves (...)

2017-07-24 07:55 UTC, lreficent commented on stock_account_operating_unit/model/stock_quant.py
> +                (journal_id, acc_src, acc_dest, acc_valuation) = data
`(journal_id, acc_src, acc_dest, acc_valuation) = move._get_accounting_data_for_valuation()`? So you don't use the intermediate variable `data`?

2017-07-25 14:47 UTC, aheficent commented
@lreficent Thank you for your review. I just realized that the check was not needed because is not possible to create a not internal locations: https://github.com/OCA/operating-unit/blob/10.0/stock_operating_unit/model/stock.py#L78 The UserError will never be triggered so cannot be tested

2017-07-26 08:01 UTC, lreficent commented
@aheficent great, this is good from my side now!

2017-07-26 08:01 UTC, LoisRForgeFlow approved these changes

2018-04-10 11:26 UTC, merged