[17.0][FIX] crm_operating_unit: warning in logs
OCA/operating-unit pull request #718
Opened 2024-10-15 06:22 UTC by gurneyalex

When crm_operating_unit is installed, warning messages are sent to the Odoo logs:

WARNING odoodb_test odoo.fields: Redundant default on crm.lead.operating_unit_id

This is caused by the setting of a default value on a related field.

We change the field to be computed, read-only with a compute method which implements the logic of the default value in case the team of the lead does not have an operating unit.

2024-10-15 07:52 UTC, yankinmax approved these changes

2024-10-15 09:31 UTC, AaronHForgeFlow approved these changes
LGTM

2024-10-15 09:35 UTC, AaronHForgeFlow commented on crm_operating_unit/models/crm_lead.py
> +    @api.depends("team_id.operating_unit_id")
shouldn't we add the team_id also in the api.depends?

2025-03-23 12:39 UTC, rvalyi commented
@gurneyalex , please just add the team_id also in the depends as @AaronHForgeFlow suggested as changing the team might also change the operating unit...

2025-03-23 12:40 UTC, rvalyi requested changes
@gurneyalex , please just add the team_id also in the depends as @AaronHForgeFlow suggested as changing the team might also change the operating unit...

2025-09-07 12:32 UTC, closed without merging

2026-01-13 15:59 UTC, vvrossem commented
superseded by https://github.com/OCA/operating-unit/pull/826