[18.0][MIG] mrp_operating_unit: Migration to 18.0
OCA/operating-unit pull request #722
Opened 2024-12-10 13:04 UTC by BT-dlagin

2025-03-10 10:53 UTC, BT-dmoreno approved these changes

2025-03-10 11:10 UTC, BT-dlagin commented
@OCA/accounting-maintainers  hello, kindly requesting a review.
Thanks a lot.

2025-03-10 11:36 UTC, BT-ojossen requested changes
Just one small thing the rest lgtm

2025-03-10 11:36 UTC, BT-ojossen commented on mrp_operating_unit/models/mrp.py
> +            if picking_type_id:
[Change] I would remove the "if", better to have it set to false if there was a picking_type_id and now we have nothing to set

2025-03-10 14:36 UTC, BT-dlagin commented on mrp_operating_unit/models/mrp.py
> +            if picking_type_id:
Hello, tried suggested changes, but as it broke unit tests I would suggest to keep the code untouched :)

2025-03-10 14:42 UTC, BT-cserra approved these changes

2025-03-10 14:49 UTC, BT-ojossen approved these changes

2025-03-10 15:29 UTC, JordiBForgeFlow commented
@AaronHForgeFlow

2025-03-10 20:42 UTC, AaronHForgeFlow approved these changes
LGTM! Just a minor comment

2025-03-10 20:42 UTC, AaronHForgeFlow commented on mrp_operating_unit/models/mrp.py
> +                    _(
self.env._

2025-03-11 08:14 UTC, BT-dlagin commented on mrp_operating_unit/models/mrp.py
> +                    _(
@AaronHForgeFlow Hi, change applied, can you check and possibly merge, thanks!

2025-03-11 08:23 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2025-03-11 08:24 UTC, AaronHForgeFlow commented on mrp_operating_unit/models/mrp.py
> +                    _(
Thank you

2025-03-11 08:28 UTC, merged