[9.0][FIX]operating unit when onchange picking type
OCA/operating-unit pull request #76
Opened 2017-06-19 08:39 UTC by aheficent

The onchange method is not compatible with readonly fields. 

When changing the picking type the operating unit of the warehouse was not been stored.

As there's  a constraint that checks for incompatibilities between the operating unit in the warehouse and in the picking I think the field operating_unit_id in the picking can be editable.

This PR Includes another small fix in the method  `_check_warehouse_operating_unit`

2017-06-19 08:46 UTC, aheficent commented
@eficent @darshan-serpent

2017-06-19 09:15 UTC, serpentcs-dev1 approved these changes
Code Review and tested on runbot 

LGTM :+1: 

Yes it seems that when a field is set as readonly, the values will not be stored in the database.

2017-06-19 10:26 UTC, aheficent commented
Yes @darshan-serpent when the field is readonly it won't store the field even if the readonly is just in the view :open_mouth:

2017-06-20 08:55 UTC, MiquelRForgeFlow approved these changes

2017-06-20 08:58 UTC, MiquelRForgeFlow requested changes

2017-06-20 08:58 UTC, mreficent commented on stock_operating_unit/model/stock.py
> +                if rec.operating_unit_id != w.operating_unit_id:
I think that `if` is duplicated.

2017-06-20 10:07 UTC, aheficent commented
Thank you for your review @mreficent Your request have been attended :call_me_hand:

2017-06-20 10:21 UTC, MiquelRForgeFlow approved these changes

2017-06-20 10:40 UTC, aheficent commented
I just squashed the commits. No code affected.

2017-06-20 10:57 UTC, LoisRForgeFlow approved these changes
:+1:

2017-08-28 14:14 UTC, merged