10.0 purchase requisition operating unit
OCA/operating-unit pull request #81
Opened 2017-07-06 12:37 UTC by darshan-serpent

Purchase Requisition with Operating Units
=========================================

This module introduces the following features:

* Security rules are defined to ensure that users can only see the Purchase Requisition of that Operating Units in which they are allowed access to.

* Ensures that Purchase Requisition and the Warehouse in picking type belongs to the same Operating Unit (OU) .

* When the user creates a Purchase Order (PO) from the purchase requisition the operating unit is passed to that PO.

* Sets default Picking type whoes Operating Unit (OU) in Warehouse matches to that of the User.

2017-07-06 12:47 UTC, darshan-serpent commented
@aheficent Please review code.

2017-07-06 12:57 UTC, nikul-serpentcs commented
@aheficent Please review code.

2017-07-06 13:58 UTC, AaronHForgeFlow requested changes
Only code review

2017-07-06 13:58 UTC, aheficent commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                    raise UserError(_('Configuration error!\nThe Operating \
\n is not need, just close the quotes and open those again in the next line

2017-07-06 13:58 UTC, aheficent commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                self.picking_type_id = types[:1]
Why don't you use the first?

2017-07-07 05:04 UTC, nikul-serpentcs commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                    raise UserError(_('Configuration error!\nThe Operating \
@aheficent Removed '\n' and quotes open next line.
Please review code.

2017-07-07 05:05 UTC, nikul-serpentcs commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                self.picking_type_id = types[:1]
@aheficent 
removed first.

2017-07-07 05:47 UTC, nikul-serpentcs commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                self.picking_type_id = types[:1]
@aheficent 
Python slicing in find first value.

2017-07-07 10:06 UTC, darshan-serpent commented on purchase_requisition_operating_unit/__manifest__.py
> +    "depends": ["purchase_requisition",
@aheficent Waiting for [#368](https://github.com/OCA/purchase-workflow/pull/368) to get merged.

I guess then we need to add `purchase-workflow` to the oca_dependencies, right?

Don't know though why the travis is green now?!

2017-07-10 14:03 UTC, AaronHForgeFlow approved these changes
:+1: LGTM Thanks. Can you please squash the commits before this is merged?

2017-08-21 05:42 UTC, nikul-serpentcs commented
@aheficent  squashed commits, Please check it.

2017-09-04 13:28 UTC, aheficent commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                raise UserError(_('The Company in the Purchase Requisition and'
I'll be great if you include and assertRaises in the test for this one :medal_sports:

2017-09-06 09:19 UTC, nikul-serpentcs commented
@aheficent included assertRaises in the test case, Please check it.

2017-09-06 09:22 UTC, AaronHForgeFlow approved these changes
@nikul-serpentcs codecov covers 100% of the lines don't know why it's red

2017-09-06 09:57 UTC, nikul-serpentcs commented
@aheficent Rebased branch and Mr.Travis is Happy.

2018-04-10 10:51 UTC, aheficent commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                    raise UserError(_('Configuration error! The Operating '
Can you avoid exclamation marks in the error messages? People may feel bad when getting a message like this

2018-04-10 10:52 UTC, aheficent commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                raise UserError(_("No Warehouse found with the "
Same here

2018-06-27 11:56 UTC, mreficent commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                    raise UserError(_('Configuration error, The Operating '
but the `,` should be a `.` @aheficent

2018-06-27 12:11 UTC, aheficent commented on purchase_requisition_operating_unit/model/purchase_requisition.py
> +                    raise UserError(_('Configuration error, The Operating '
done @mreficent  thanks

2018-06-27 13:18 UTC, MiquelRForgeFlow approved these changes

2021-12-05 12:22 UTC, closed without merging